### PR TITLE
Fix typo in 'reasign'

### PR DESCRIPTION
**Pull request by emerald000**
Typos fix.

### CODE REVIEW

**Comment by psikoi** [comment]
Oops! Thanks for noticing, could you squash those into a single commit? And with a more appropriate commit message, like "Fix reassign typo"

**Comment by emerald000** [comment]
Can you just squash and merge? I was hoping to just use the Github edit tools and not having to download everything with git just for this.

**Comment by psikoi** [comment]
Sure, are you sure these are the only mentions of that word? I'm not currently on the computer to check

**Comment by emerald000** [comment]
Yeah, those are the only 3 instances in the repo.

**Comment by emerald000** [comment]
Turns out Github sucks and didn't give all the instances.

So I ended up doing things correctly anyway.

**Comment by psikoi** [comment]
I was about to double check myself, seems correct now! Thanks

**Pull request merged**
